version: "3.9"

services:
  web:
    container_name: nginx2
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - ./src/:/app

  app:
    container_name: php2
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/app
    ports:
      - 5173:5173
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lara_doc_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3309:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
